declare module 'react-mdc-web/lib' {
  import * as React from 'react'

  class Button extends React.Component<any, {}> {}
  class Card extends React.Component<any, {}> {}
  class CardHeader extends React.Component<any, {}> {}
  class CardTitle extends React.Component<any, {}> {}
  class CardText extends React.Component<any, {}> {}
  class CardActions extends React.Component<any, {}> {}
  class Dialog extends React.Component<any, {}> {}
  class Drawer extends React.Component<any, {}> {}
  class Elevation extends React.Component<any, {}> {}
  class FAB extends React.Component<any, {}> {}
  class Grid extends React.Component<any, {}> {}
  class GridList extends React.Component<any, {}> {}
  class Tile extends React.Component<any, {}> {}
  class TilePrimary extends React.Component<any, {}> {}
  class TileSecondary extends React.Component<any, {}> {}
  class IconToggle extends React.Component<any, {}> {}
  class LinearProgress extends React.Component<any, {}> {}
  class List extends React.Component<any, {}> {}
  class ListItem extends React.Component<any, {}> {}
  class Menu extends React.Component<any, {}> {}
  class MenuAnchor extends React.Component<any, {}> {}
  class MenuItem extends React.Component<any, {}> {}
  class Radio extends React.Component<any, {}> {}
  class FormField extends React.Component<any, {}> {}
  class Slider extends React.Component<any, {}> {}
  class Snackbar extends React.Component<any, {}> {}
  class Switch extends React.Component<any, {}> {}
  class Tabbar extends React.Component<any, {}> {}
  class Tab extends React.Component<any, {}> {}
  class Cell extends React.Component<any, {}> {}
  class Textfield extends React.Component<any, {}> {}
  class Toolbar extends React.Component<any, {}> {}
  class ToolbarRow extends React.Component<any, {}> {}
  class ToolbarSection extends React.Component<any, {}> {}
  class ToolbarTitle extends React.Component<any, {}> {}
  class Display4 extends React.Component<any, {}> {}
  class Display3 extends React.Component<any, {}> {}
  class Display2 extends React.Component<any, {}> {}
  class Display1 extends React.Component<any, {}> {}
  class Headline extends React.Component<any, {}> {}
  class Title extends React.Component<any, {}> {}
  class Subheading2 extends React.Component<any, {}> {}
  class Subheading1 extends React.Component<any, {}> {}
  class Body2 extends React.Component<any, {}> {}
  class Body1 extends React.Component<any, {}> {}
  class Caption extends React.Component<any, {}> {}
}